SELECT * FROM customer;

 --Q1 what is the total revenue generated by male and female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

 --Q2 Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' 
AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer);
 --Q3. What is the average age of customers by gender?
SELECT gender, AVG(age) as average_age 
FROM customer 
GROUP BY gender;

 --Q4. Which location has the highest number of unique customers?
SELECT location, COUNT(customer_id) as total_customers 
FROM customer 
GROUP BY location 
ORDER BY total_customers DESC;

 --Q5. What is the most popular item category purchased?
SELECT category, COUNT(item_purchased) as total_sold 
FROM customer 
GROUP BY category 
ORDER BY total_sold DESC;

--Q6. What is the average purchase amount for each category?
SELECT category, AVG(purchase_amount) as avg_spend 
FROM customer 
GROUP BY category 
ORDER BY avg_spend DESC;

--Q7. How many customers used a promo code vs no promo code?
SELECT promo_code_used, COUNT(customer_id) as customer_count 
FROM customer 
GROUP BY promo_code_used;

 --Q8. What is the breakdown of payment methods used by customers?
SELECT payment_method, COUNT(customer_id) as transaction_count 
FROM customer 
GROUP BY payment_method 
ORDER BY transaction_count DESC;

 --Q9. Are customers who are repeat buyers more than 5 previous purchases?
SELECT subscription_status, COUNT(customer_id) as repeat_buyers 
FROM customer 
WHERE previous_purchases > 5 
GROUP BY subscription_status;

 --Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) as total_revenue 
FROM customer 
GROUP BY age_group 
ORDER BY total_revenue DESC;